config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :myfiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  get "/api/v1/myfiles/:id", to: "myfiles#getFile"

  post "/api/v1/myfiles/", to: "myfiles#addFile"

  delete "/api/v1/myfiles/:id", to: "myfiles#deleteFile"

  patch "/api/v1/myfiles/:id", to: "myfiles#editFile"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/myfile.rb
class Myfile < ApplicationRecord

    has_one_attached :file_att
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/myfiles_controller.rb
class MyfilesController < InheritedResources::Base


    def getFile
      file_ = Myfile.find_by(id: params[:id])

      if file_.present?
        p rails_blob_path(file_.file_att)
        render json: {id: file_[:id], filename: file_[:filename], status: file_[:status],
          file_url: url_for(file_.file_att),created_at: file_[:created_at], updated_at: file_[:updated_at]}, status: :ok
      else
        head :not_found
      end
    end

    
    def editFile

      f = Myfile.find(params[:id]);
      if (f.update(update_params));
        render json: {status: "ok"}
      else
        render json: {error: "error"}
      end

    end
    def addFile

      myfile = Myfile.new(create_params);

      if (myfile.save)
        render json: {status: "ok"}
      else
        render json: {error: "error"}
      end
    end
    def deleteFile
      f = Myfile.find(params[:id]);
      if (f.destroy)
        render json: {status: "ok"}
      else
        render json: {error: "error"}
      end
    end

    def create_params
      params.require().permit(:filename, :status, :file_att)
    end

    def update_params
      params.permit(:filename, :status, :file_att)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myfiles_helper.rb
module MyfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveStorageApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/myfiles/_form.html.erb
<%= form_with(model: myfile) do |form| %>
  <% if myfile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(myfile.errors.count, "error") %> prohibited this myfile from being saved:</h2>

      <ul>
        <% myfile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :filename, style: "display: block" %>
    <%= form.text_field :filename %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :file_att, style: "display: block" %>
    <%= form.file_field :file_att %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/myfiles/_myfile.html.erb
<div id="<%= dom_id myfile %>">
  <p>
    <strong>Filename:</strong>
    <%= myfile.filename %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= myfile.status %>
  </p>

  <p>
    <strong>File att:</strong>
    <%= link_to myfile.file_att.filename, myfile.file_att if myfile.file_att.attached? %>
  </p>

</div>

app/views/myfiles/edit.html.erb
<h1>Editing myfile</h1>

<%= render "form", myfile: @myfile %>

<br>

<div>
  <%= link_to "Show this myfile", @myfile %> |
  <%= link_to "Back to myfiles", myfiles_path %>
</div>

app/views/myfiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Myfiles</h1>

<div id="myfiles">
  <% @myfiles.each do |myfile| %>
    <%= render myfile %>
    <p>
      <%= link_to "Show this myfile", myfile %>
    </p>
  <% end %>
</div>

<%= link_to "New myfile", new_myfile_path %>

app/views/myfiles/new.html.erb
<h1>New myfile</h1>

<%= render "form", myfile: @myfile %>

<br>

<div>
  <%= link_to "Back to myfiles", myfiles_path %>
</div>

app/views/myfiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @myfile %>

<div>
  <%= link_to "Edit this myfile", edit_myfile_path(@myfile) %> |
  <%= link_to "Back to myfiles", myfiles_path %>

  <%= button_to "Destroy this myfile", @myfile, method: :delete %>
</div>